### ISSUE TITLE
Adding an example datalog.dl tbox_name.txt

### ISSUE THREAD

**Issue by sairahul** [ghxiao/nrdatalog2sql#2]
It would be helpful to have an example datalog.dl and tbox_name.txt files. It would be easier to try and test the current code with an example.

**Comment by ghxiao** [comment]
Hi, I uploaded an example query file. Now you can try the following example to see an example SQL generation. 

$ ./src/datalog/nrdatalog2sql.py data/q1.dl data/LUBM-ex-20_tbox-name.txt 

However please be aware that OWLGres is not publicly available any more. So the SQL cannot be evaluated directly.

**Comment by sairahul** [comment]
Thanks for adding an example. I tested and it works. Is there any other system that is similar to OWLGres ?

**Comment by ghxiao** [comment]
If you are interested in accessing existing relational DBs via SPARQL, check Ontop. https://github.com/ontop/ontop

OWLGres now becomes Stardog which is a triple store (which also includes Ontop).

**Comment by sairahul** [comment]
Thanks a lot. I will look into it. I will close this ticket.
